import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpClientModule} from '@angular/common/http';
// import { HttpModule} from '@angular/common/http';

// Component
import { AppComponent } from './app.component';
import { DetailComponent } from './detail.component';
import { ProductComponent } from './products/product.component';
import { MyUpperPipe } from './products/myUpper.pipe';
import { DiscountedPipe } from './products/discount.pipe';
import { ProductSearchPipe } from './products/productSearch.pipe';
import { StarComponent } from './shared/star.component';
import { ProductService } from './products/product.service';
import { HomeComponent } from './home/home.component';
import { OrderComponent } from './orders/order.component';
import { ProductDetailComponent } from './products/product-detail.component';
import { NotFoundComponent } from './shared/NotFound.component';
import { ProductModule } from './products/product.module';


@NgModule({

    // We declare all Component & Pipe
    declarations: [
        AppComponent,
        DetailComponent,
        ProductComponent,
        MyUpperPipe,
        DiscountedPipe,
        ProductSearchPipe,
        StarComponent,
        HomeComponent,
        OrderComponent,
        ProductDetailComponent,
        NotFoundComponent
    ],

    // All Module
    imports: [
        BrowserModule,
        FormsModule,
        RouterModule.forRoot([
            {path: 'products', component: ProductComponent},
            {path: 'products/:id', component: ProductDetailComponent},
            {path: 'orders', component: OrderComponent},
            {path: 'home', component: HomeComponent},
            {path: '', redirectTo: 'home' , pathMatch: 'full'},
            {path: '**', component: NotFoundComponent},
        ]),
        HttpClientModule,
        ProductModule
        // HttpModule
    ],

    // Only First Component
    bootstrap: [
        AppComponent
    ],

    // All Services
    providers: [
        ProductService
    ]

})

export class AppModule {

}
